name: Build Flutter App

on:
  push:
    tags:
      - 'v*'
    
jobs:

  # ----------------------------
  # Windows build
  # ----------------------------
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: |
          flutter config --enable-windows-desktop
          flutter pub get
      - name: Patch opus_flutter_windows
        run: |
          $symlink = "windows/flutter/ephemeral/.plugin_symlinks/opus_flutter_windows/windows"
          if (-not (Test-Path $symlink)) { New-Item -ItemType Directory -Path $symlink -Force }
      - run: flutter build windows --release
        env:
          CMAKE_POLICY_VERSION_MINIMUM: 3.5

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

  # ----------------------
  # LINUX BUILD
  # ----------------------
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libsecret-1-dev \
            libayatana-appindicator3-dev \
            libopus0 \
            gstreamer1.0-tools \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            libpulse-dev

      - run: |
          flutter config --enable-linux-desktop
          flutter pub get
      - run: flutter build linux

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/

  # ----------------------
  # ANDROID BUILD
  # ----------------------
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: flutter pub get

      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
